// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/pools","parentId":"@@/global-layout","id":"1"},"2":{"path":"/login","layout":false,"id":"2"},"3":{"path":"/pools","name":"线程池","parentId":"@@/global-layout","id":"3"},"4":{"path":"/metrics","name":"可视化监控","parentId":"@@/global-layout","id":"4"},"5":{"path":"/*","redirect":"/","parentId":"@@/global-layout","id":"5"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__login" */'@/pages/login.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__pools" */'@/pages/pools.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__metrics" */'@/pages/metrics.tsx')),
'5': React.lazy(() => import('./EmptyRoute')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'E:/code/dynamic-thread-pool/dynamic-thread-pool-web-frontend/src/layouts/index.tsx')),
},
  };
}
