server:
  port: 8092

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 动态线程池配置
dynamic-thread-pool:
  registry:
    redis:
      host: 192.168.67.129
      port: 16379
      password: bancheng666..
    report-cron: "0/10 * * * * ?"
  alarm:
    enabled: true
    access-token:
      ding-ding: xxx
    use-platform:
      - "DingDing"